import {
  Briefcase,
  Building2,
  CalendarDays,
  ClipboardList,
  CreditCard,
  FileBadge2,
  FileSpreadsheet,
  Files,
  HandCoins,
  Headset,
  LayoutDashboard,
  LineChart,
  Receipt,
  ScrollText,
  Settings2,
  ShieldCheck,
  UserCircle2,
  Users,
} from 'lucide-react';

export const dashboardConfigs = {
  admin: {
    title: 'Admin Console',
    subtitle: 'Coordinate leads, partners, clients, fulfilment, and post-sales workflows.',
    basePath: '/admin',
    items: [
      { label: 'Overview', path: '/admin/dashboard', icon: LayoutDashboard },
      { label: 'Leads', path: '/admin/leads', icon: Users },
      { label: 'Bookings', path: '/admin/bookings', icon: CalendarDays },
      { label: 'Customers', path: '/admin/customers', icon: UserCircle2 },
      { label: 'Vendors', path: '/admin/vendors', icon: Briefcase },
      { label: 'Quotations', path: '/admin/quotations', icon: ScrollText },
      { label: 'Payments', path: '/admin/payments', icon: HandCoins },
      { label: 'Plans', path: '/admin/plans', icon: Settings2 },
      { label: 'Services', path: '/admin/services', icon: Headset },
      { label: 'Documents', path: '/admin/documents', icon: Files },
      { label: 'Support', path: '/admin/support', icon: ShieldCheck },
      { label: 'Enquiries', path: '/admin/enquiries', icon: ClipboardList },
      { label: 'Calculator', path: '/admin/calculator', icon: LineChart },
    ],
  },
  vendor: {
    title: 'Vendor Workspace',
    subtitle: 'Track assigned opportunities, fulfil jobs, and stay aligned on delivery.',
    basePath: '/vendor',
    items: [
      { label: 'Overview', path: '/vendor/dashboard', icon: LayoutDashboard },
      { label: 'Assigned Leads', path: '/vendor/leads', icon: Users },
      { label: 'Quotations', path: '/vendor/quotations', icon: ScrollText },
      { label: 'Bookings & Visits', path: '/vendor/bookings', icon: CalendarDays },
      { label: 'Installations', path: '/vendor/installations', icon: Building2 },
      { label: 'Payments', path: '/vendor/payments', icon: CreditCard },
      { label: 'Service Requests', path: '/vendor/services', icon: Headset },
      { label: 'Profile', path: '/vendor/profile', icon: UserCircle2 },
      { label: 'Documents', path: '/vendor/documents', icon: Files },
    ],
  },
  client: {
    title: 'Client Portal',
    subtitle: 'Follow your solar journey from enquiry to installation, finance, and support.',
    basePath: '/client',
    items: [
      { label: 'Overview', path: '/client/dashboard', icon: LayoutDashboard },
      { label: 'Profile', path: '/client/profile', icon: UserCircle2 },
      { label: 'Enquiries', path: '/client/enquiries', icon: ClipboardList },
      { label: 'Quotations', path: '/client/quotations', icon: ScrollText },
      { label: 'Plan Comparison', path: '/client/plan-comparison', icon: FileSpreadsheet },
      { label: 'Booking Status', path: '/client/bookings', icon: CalendarDays },
      { label: 'Installation Progress', path: '/client/installation-progress', icon: Building2 },
      { label: 'Payments', path: '/client/payments', icon: CreditCard },
      { label: 'Finance Status', path: '/client/finance', icon: HandCoins },
      { label: 'Service Requests', path: '/client/services', icon: Headset },
      { label: 'Invoices', path: '/client/invoices', icon: Receipt },
      { label: 'Warranty Documents', path: '/client/documents', icon: FileBadge2 },
      { label: 'Support', path: '/client/support', icon: ShieldCheck },
    ],
  },
};
